;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        complete-symbol
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        paredit-backward
        paredit-backward-kill-word
        paredit-forward
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-splice-sexp
        paredit-wrap-round
        slime-autodoc-space
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        find-file
        paredit-backward-slurp-sexp
        paredit-forward-barf-sexp
        paredit-splice-sexp-killing-backward
        paredit-splice-sexp-killing-forward
        slime-compile-defun
        switch-to-buffer
        ))
